title = "configuration for local environment"

[database]
host = "localhost"
port = 35432
user = "postgres"
password = "password" # dont write! in production,staging environment. 
dbName = "imap_agent"

 
